### ISSUE TITLE
Can we add my Logger class?

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/sidetrack#1]
I really like sidetrack, I also have some logging code (for more traditional logging) that I wind up including over and overy. Can we add this to sidetrack? I've push up a branch called logger-class that contains the class I use and have added in the __init__.py.

Thanks,

Robert

**Comment by mhucka** [comment]
Can you point me to some examples of how you use the Logger class in practice?

**Comment by rsdoiel** [comment]
Yes, happy to. I'll close this pull request then add examples and tests then do new pull request when I think I have something good. Thanks, Robert

**Comment by mhucka** [comment]
Really I was only wondering about an example where it gets used in current code. There must be a repo on github where it's used? I'm wondering about things like the pid argument, also where/how the Logger object gets created and passed around, etc.

**Comment by rsdoiel** [comment]
I'm eprinttools is the most recent place. The examples are typically of the
form

import os
from eprinttools import Logger

# At the start of your code you create a logger instance to use. E.g.

log = Logger(os.getpid())

# Do stuff that needs log output

log.print("This is just a log message") # this would print out timestamp,
pid prefixed text before the message passed.

# Debug output can be done with

if __debug__: log.print("Some debug stuff here")

if bad_thing_happened:
      log.fatal("Something really bad happened. I'm quitting now.")



I also use a similar approach in the searchtools package I'm developing for
supporting LunrJS and Elasticsearch
indexers and UI (but I am still writing that as I only created it today).

Things I think I should add before accepting the pull request.  I should
have my log command let you easily pick the
file to log to or use standard output or standard error. I don't have that
there now.

Like your sidetrack code it's a pattern I keep rewriting and reimplementing
so I'd like to see if consolidated into something
that just works when I need it (e.g. like your sidetrack log method).

Logger is sorta based on the Go standard logging package.

Thanks,

Robert

**Comment by mhucka** [comment]
Thanks for the info. I get the idea now. 

A couple of things about the goals for sidetrack:

* Operations like "alert" and "warning" feel like they belong to a different layer. In my other code, I have a ui.py package that implements message utilities for that purpose, and _those_ call the logging function. In other words, a different abstraction layer.
* I was trying to make the invocation as short as possible, to make code lines short (keeping as often as possible to 80 chars or less). This was why the function is log(...) rather than log.print(...).

That said, one thing that would be easy to do is provide a way to pass an optional argument to `set_debug` in Sidetrack to add a user-defined prefix to the messages. That would allow passing the pid down. Would that be useful?

**Comment by rsdoiel** [comment]
It could be. Or even just a flag that optionally inserts the timestamp/pid
in the logging also. On the other hand, maybe logger.py should just be in a
different package.
I use logging both in a debugging sense, a monitoring because it is new
software sense and of course just to see where a long running process is so
I can make decisions about allowing it to continue, wait for completion or
confirmation that everything went OK after.

It's always a balance between feature creep, package space explosion and
easy of maintenance (simple, more specific is usually easier to maintain).
Not sure the right path.
I will think about it over the weekend.

Happy Friday!

Robert

**Comment by mhucka** [comment]
OK, in the interim, in the next version of Sidetrack, `set_debug(...)` will a new optional argument named `extra`.  The value can be text that will be printed before the rest of the logged message. The `extra` string can contain [Python logging package % formatting directives](https://docs.python.org/library/logging.html#logrecord-attributes). So for example, it will be possible to insert the PID by adding the argument `extra = "%(process)d"`.

**Comment by rsdoiel** [comment]
That's cool.

Thanks,

Robert
